version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://ep_user:Planner123!@db/ep_db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ep_db
      POSTGRES_USER: ep_user
      POSTGRES_PASSWORD: Planner123!

  # experimental to automate the migration on fresh build
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["bundle", "exec", "rails", "db:migrate"]
    depends_on:
      - app
      - db


volumes:
  postgres_data:
